version: "3"

services:
  web:
    container_name: simple-app
    build: .
    # command: npm start
    volumes:
      - .:/app/
      # - ./scripts/nginx/:/etc/nginx/vhost.d/
      - ./scripts/nginx/:/etc/nginx/conf.d/
    ports:
      - 3000:3000
    # restart: always
    environment:
      - VIRTUAL_HOST=localhost
      # - VIRTUAL_HOST=test.*
      - VIRTUAL_PORT=3000
      - NODE_ENV=production

networks:
  default:
    external:
      name: nginx-proxy
